//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBibliotecaBO.Reportes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", ConfigurationName="Reportes.Reportes")]
    public interface Reportes {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reportePublicacionesRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reportePublicacionesResponse" +
            "")]
        SoftBibliotecaBO.Reportes.reportePublicacionesResponse reportePublicaciones(SoftBibliotecaBO.Reportes.reportePublicacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reportePublicacionesRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reportePublicacionesResponse" +
            "")]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reportePublicacionesResponse> reportePublicacionesAsync(SoftBibliotecaBO.Reportes.reportePublicacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechaMin del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteSolicitudesRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteSolicitudesResponse")]
        SoftBibliotecaBO.Reportes.reporteSolicitudesResponse reporteSolicitudes(SoftBibliotecaBO.Reportes.reporteSolicitudesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteSolicitudesRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteSolicitudesResponse")]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteSolicitudesResponse> reporteSolicitudesAsync(SoftBibliotecaBO.Reportes.reporteSolicitudesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechaRegMin del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteMiembrosRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteMiembrosResponse")]
        SoftBibliotecaBO.Reportes.reporteMiembrosResponse reporteMiembros(SoftBibliotecaBO.Reportes.reporteMiembrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteMiembrosRequest", ReplyAction="http://servicios.softbiblioteca.pucp.edu.pe/Reportes/reporteMiembrosResponse")]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteMiembrosResponse> reporteMiembrosAsync(SoftBibliotecaBO.Reportes.reporteMiembrosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reportePublicacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reportePublicaciones", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reportePublicacionesRequestBody Body;
        
        public reportePublicacionesRequest() {
        }
        
        public reportePublicacionesRequest(SoftBibliotecaBO.Reportes.reportePublicacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reportePublicacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cantPrestamosMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cantPrestamosMax;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int incluirVirtuales;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idUniversidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int limite;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string descripcion;
        
        public reportePublicacionesRequestBody() {
        }
        
        public reportePublicacionesRequestBody(int cantPrestamosMin, int cantPrestamosMax, int incluirVirtuales, int idUniversidad, int limite, string descripcion) {
            this.cantPrestamosMin = cantPrestamosMin;
            this.cantPrestamosMax = cantPrestamosMax;
            this.incluirVirtuales = incluirVirtuales;
            this.idUniversidad = idUniversidad;
            this.limite = limite;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reportePublicacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reportePublicacionesResponse", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reportePublicacionesResponseBody Body;
        
        public reportePublicacionesResponse() {
        }
        
        public reportePublicacionesResponse(SoftBibliotecaBO.Reportes.reportePublicacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reportePublicacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public reportePublicacionesResponseBody() {
        }
        
        public reportePublicacionesResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reporteSolicitudesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reporteSolicitudes", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reporteSolicitudesRequestBody Body;
        
        public reporteSolicitudesRequest() {
        }
        
        public reporteSolicitudesRequest(SoftBibliotecaBO.Reportes.reporteSolicitudesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reporteSolicitudesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaMax;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string estadoDePrestamos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idUniversidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int mostrarONoReservas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string descripcion;
        
        public reporteSolicitudesRequestBody() {
        }
        
        public reporteSolicitudesRequestBody(int idUsuario, string fechaMin, string fechaMax, string estadoDePrestamos, int idUniversidad, int mostrarONoReservas, string descripcion) {
            this.idUsuario = idUsuario;
            this.fechaMin = fechaMin;
            this.fechaMax = fechaMax;
            this.estadoDePrestamos = estadoDePrestamos;
            this.idUniversidad = idUniversidad;
            this.mostrarONoReservas = mostrarONoReservas;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reporteSolicitudesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reporteSolicitudesResponse", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reporteSolicitudesResponseBody Body;
        
        public reporteSolicitudesResponse() {
        }
        
        public reporteSolicitudesResponse(SoftBibliotecaBO.Reportes.reporteSolicitudesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reporteSolicitudesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public reporteSolicitudesResponseBody() {
        }
        
        public reporteSolicitudesResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reporteMiembrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reporteMiembros", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reporteMiembrosRequestBody Body;
        
        public reporteMiembrosRequest() {
        }
        
        public reporteMiembrosRequest(SoftBibliotecaBO.Reportes.reporteMiembrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reporteMiembrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaRegMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaRegMax;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cantSancionesMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantSancionesMax;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idUniversidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int limiteUsuarios;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string descripcion;
        
        public reporteMiembrosRequestBody() {
        }
        
        public reporteMiembrosRequestBody(string fechaRegMin, string fechaRegMax, int cantSancionesMin, int cantSancionesMax, int idUniversidad, int limiteUsuarios, string descripcion) {
            this.fechaRegMin = fechaRegMin;
            this.fechaRegMax = fechaRegMax;
            this.cantSancionesMin = cantSancionesMin;
            this.cantSancionesMax = cantSancionesMax;
            this.idUniversidad = idUniversidad;
            this.limiteUsuarios = limiteUsuarios;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reporteMiembrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reporteMiembrosResponse", Namespace="http://servicios.softbiblioteca.pucp.edu.pe/", Order=0)]
        public SoftBibliotecaBO.Reportes.reporteMiembrosResponseBody Body;
        
        public reporteMiembrosResponse() {
        }
        
        public reporteMiembrosResponse(SoftBibliotecaBO.Reportes.reporteMiembrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class reporteMiembrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public reporteMiembrosResponseBody() {
        }
        
        public reporteMiembrosResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportesChannel : SoftBibliotecaBO.Reportes.Reportes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesClient : System.ServiceModel.ClientBase<SoftBibliotecaBO.Reportes.Reportes>, SoftBibliotecaBO.Reportes.Reportes {
        
        public ReportesClient() {
        }
        
        public ReportesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBibliotecaBO.Reportes.reportePublicacionesResponse SoftBibliotecaBO.Reportes.Reportes.reportePublicaciones(SoftBibliotecaBO.Reportes.reportePublicacionesRequest request) {
            return base.Channel.reportePublicaciones(request);
        }
        
        public byte[] reportePublicaciones(int cantPrestamosMin, int cantPrestamosMax, int incluirVirtuales, int idUniversidad, int limite, string descripcion) {
            SoftBibliotecaBO.Reportes.reportePublicacionesRequest inValue = new SoftBibliotecaBO.Reportes.reportePublicacionesRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reportePublicacionesRequestBody();
            inValue.Body.cantPrestamosMin = cantPrestamosMin;
            inValue.Body.cantPrestamosMax = cantPrestamosMax;
            inValue.Body.incluirVirtuales = incluirVirtuales;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.limite = limite;
            inValue.Body.descripcion = descripcion;
            SoftBibliotecaBO.Reportes.reportePublicacionesResponse retVal = ((SoftBibliotecaBO.Reportes.Reportes)(this)).reportePublicaciones(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reportePublicacionesResponse> SoftBibliotecaBO.Reportes.Reportes.reportePublicacionesAsync(SoftBibliotecaBO.Reportes.reportePublicacionesRequest request) {
            return base.Channel.reportePublicacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reportePublicacionesResponse> reportePublicacionesAsync(int cantPrestamosMin, int cantPrestamosMax, int incluirVirtuales, int idUniversidad, int limite, string descripcion) {
            SoftBibliotecaBO.Reportes.reportePublicacionesRequest inValue = new SoftBibliotecaBO.Reportes.reportePublicacionesRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reportePublicacionesRequestBody();
            inValue.Body.cantPrestamosMin = cantPrestamosMin;
            inValue.Body.cantPrestamosMax = cantPrestamosMax;
            inValue.Body.incluirVirtuales = incluirVirtuales;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.limite = limite;
            inValue.Body.descripcion = descripcion;
            return ((SoftBibliotecaBO.Reportes.Reportes)(this)).reportePublicacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBibliotecaBO.Reportes.reporteSolicitudesResponse SoftBibliotecaBO.Reportes.Reportes.reporteSolicitudes(SoftBibliotecaBO.Reportes.reporteSolicitudesRequest request) {
            return base.Channel.reporteSolicitudes(request);
        }
        
        public byte[] reporteSolicitudes(int idUsuario, string fechaMin, string fechaMax, string estadoDePrestamos, int idUniversidad, int mostrarONoReservas, string descripcion) {
            SoftBibliotecaBO.Reportes.reporteSolicitudesRequest inValue = new SoftBibliotecaBO.Reportes.reporteSolicitudesRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reporteSolicitudesRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.fechaMin = fechaMin;
            inValue.Body.fechaMax = fechaMax;
            inValue.Body.estadoDePrestamos = estadoDePrestamos;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.mostrarONoReservas = mostrarONoReservas;
            inValue.Body.descripcion = descripcion;
            SoftBibliotecaBO.Reportes.reporteSolicitudesResponse retVal = ((SoftBibliotecaBO.Reportes.Reportes)(this)).reporteSolicitudes(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteSolicitudesResponse> SoftBibliotecaBO.Reportes.Reportes.reporteSolicitudesAsync(SoftBibliotecaBO.Reportes.reporteSolicitudesRequest request) {
            return base.Channel.reporteSolicitudesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteSolicitudesResponse> reporteSolicitudesAsync(int idUsuario, string fechaMin, string fechaMax, string estadoDePrestamos, int idUniversidad, int mostrarONoReservas, string descripcion) {
            SoftBibliotecaBO.Reportes.reporteSolicitudesRequest inValue = new SoftBibliotecaBO.Reportes.reporteSolicitudesRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reporteSolicitudesRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.fechaMin = fechaMin;
            inValue.Body.fechaMax = fechaMax;
            inValue.Body.estadoDePrestamos = estadoDePrestamos;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.mostrarONoReservas = mostrarONoReservas;
            inValue.Body.descripcion = descripcion;
            return ((SoftBibliotecaBO.Reportes.Reportes)(this)).reporteSolicitudesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftBibliotecaBO.Reportes.reporteMiembrosResponse SoftBibliotecaBO.Reportes.Reportes.reporteMiembros(SoftBibliotecaBO.Reportes.reporteMiembrosRequest request) {
            return base.Channel.reporteMiembros(request);
        }
        
        public byte[] reporteMiembros(string fechaRegMin, string fechaRegMax, int cantSancionesMin, int cantSancionesMax, int idUniversidad, int limiteUsuarios, string descripcion) {
            SoftBibliotecaBO.Reportes.reporteMiembrosRequest inValue = new SoftBibliotecaBO.Reportes.reporteMiembrosRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reporteMiembrosRequestBody();
            inValue.Body.fechaRegMin = fechaRegMin;
            inValue.Body.fechaRegMax = fechaRegMax;
            inValue.Body.cantSancionesMin = cantSancionesMin;
            inValue.Body.cantSancionesMax = cantSancionesMax;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.limiteUsuarios = limiteUsuarios;
            inValue.Body.descripcion = descripcion;
            SoftBibliotecaBO.Reportes.reporteMiembrosResponse retVal = ((SoftBibliotecaBO.Reportes.Reportes)(this)).reporteMiembros(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteMiembrosResponse> SoftBibliotecaBO.Reportes.Reportes.reporteMiembrosAsync(SoftBibliotecaBO.Reportes.reporteMiembrosRequest request) {
            return base.Channel.reporteMiembrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftBibliotecaBO.Reportes.reporteMiembrosResponse> reporteMiembrosAsync(string fechaRegMin, string fechaRegMax, int cantSancionesMin, int cantSancionesMax, int idUniversidad, int limiteUsuarios, string descripcion) {
            SoftBibliotecaBO.Reportes.reporteMiembrosRequest inValue = new SoftBibliotecaBO.Reportes.reporteMiembrosRequest();
            inValue.Body = new SoftBibliotecaBO.Reportes.reporteMiembrosRequestBody();
            inValue.Body.fechaRegMin = fechaRegMin;
            inValue.Body.fechaRegMax = fechaRegMax;
            inValue.Body.cantSancionesMin = cantSancionesMin;
            inValue.Body.cantSancionesMax = cantSancionesMax;
            inValue.Body.idUniversidad = idUniversidad;
            inValue.Body.limiteUsuarios = limiteUsuarios;
            inValue.Body.descripcion = descripcion;
            return ((SoftBibliotecaBO.Reportes.Reportes)(this)).reporteMiembrosAsync(inValue);
        }
    }
}
