[Icon_1]
Meter=Image
ImageName=#@#Images\#AppImg_1#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(1)"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(1)"]
MeterStyle=LayoutIcon
Group=Icons

[Label_1]
Meter=String
Text=#AppLbl_1#
FontColor=255,255,255,255
FontSize=#label_fontsize#
AntiAlias=1
StringAlign=Left
InlineSetting=None
DynamicVariables=1
Group=Labels
Hidden=1
MouseOverAction=[!ShowMeter Label_1][!Redraw]
MouseLeaveAction=[!HideMeter Label_1][!Redraw]

[Icon_2]
Meter=Image
ImageName=#@#Images\#AppImg_2#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(2)"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(2)"]
MeterStyle=LayoutIcon
Group=Icons

[Label_2]
Meter=String
Text=#AppLbl_2#
FontColor=255,255,255,255
FontSize=#label_fontsize#
AntiAlias=1
StringAlign=Left
InlineSetting=None
DynamicVariables=1
Group=Labels
Hidden=1
MouseOverAction=[!ShowMeter Label_2][!Redraw]
MouseLeaveAction=[!HideMeter Label_2][!Redraw]

[Icon_3]
Meter=Image
ImageName=#@#Images\#AppImg_3#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(3)"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(3)"]
MeterStyle=LayoutIcon
Group=Icons

[Label_3]
Meter=String
Text=#AppLbl_3#
FontColor=255,255,255,255
FontSize=#label_fontsize#
AntiAlias=1
StringAlign=Left
InlineSetting=None
DynamicVariables=1
Group=Labels
Hidden=1
MouseOverAction=[!ShowMeter Label_3][!Redraw]
MouseLeaveAction=[!HideMeter Label_3][!Redraw]

[Icon_4]
Meter=Image
ImageName=#@#Images\#AppImg_4#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(4)"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(4)"]
MeterStyle=LayoutIcon
Group=Icons

[Label_4]
Meter=String
Text=#AppLbl_4#
FontColor=255,255,255,255
FontSize=#label_fontsize#
AntiAlias=1
StringAlign=Left
InlineSetting=None
DynamicVariables=1
Group=Labels
Hidden=1
MouseOverAction=[!ShowMeter Label_4][!Redraw]
MouseLeaveAction=[!HideMeter Label_4][!Redraw]

[Icon_5]
Meter=Image
ImageName=#@#Images\#AppImg_5#
LeftMouseUpAction=!Execute [!CommandMeasure Animate "interact(5)"]
MouseOverAction=[!CommandMeasure "Animate" "highlight(5)"]
MeterStyle=LayoutIcon
Group=Icons

[Label_5]
Meter=String
Text=#AppLbl_5#
FontColor=255,255,255,255
FontSize=#label_fontsize#
AntiAlias=1
StringAlign=Left
InlineSetting=None
DynamicVariables=1
Group=Labels
Hidden=1
MouseOverAction=[!ShowMeter Label_5][!Redraw]
MouseLeaveAction=[!HideMeter Label_5][!Redraw]