[Variables]
TotalApps=5

AppImg_1=mysqlworkbench.png
AppDir_1="C:\Program Files\MySQL\MySQL Workbench 8.0 CE\MySQLWorkbench.exe"
AppLbl_1=MySQL WorkBench

AppImg_2=netbeans.png
AppDir_2="C:\Program Files\NetBeans-20\netbeans\bin\netbeans64.exe" "--fontsize" "19"
AppLbl_2=Netbeans 20

AppImg_3=netbeans.png
AppDir_3="C:\Program Files\NetBeans-22\netbeans\bin\netbeans64.exe" "--fontsize" "19"
AppLbl_3=Netbeans 22

AppImg_4=vsc.png
AppDir_4="C:\Users\CESAR\AppData\Local\Programs\Microsoft VS Code\Code.exe"
AppLbl_4=Visual Studio Code

AppImg_5=clion.png
AppDir_5="C:\Program Files\JetBrains\CLion 2025.2\bin\clion64.exe"
AppLbl_5=CLion
